version: "3.5"

services:
  app:
    build:
      context: .
      args:
        JDK_VERSION: ${JDK_VERSION}
        APP_MODULE_NAME: ${APP_MODULE_NAME}
        APP_VERSION: ${APP_VERSION}
    environment:
      MYSQL_PORT: db:3306
    env_file:
      - mysql-env-file.env
    ports:
      - "8081:8080"
    links:
      - db
    volumes:
      - /opt/data:/root/shelf
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "2000M"
    depends_on:
      - db

  db:
    image: mysql
    env_file:
      - mysql-env-file.env
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "2000M"