version: "3.5"

services:
  app:
    build:
      context: .
      args:
        JDK_VERSION: ${JDK_VERSION}
        APP_MODULE_NAME: ${APP_MODULE_NAME}
        APP_VERSION: ${APP_VERSION}
    environment:
      MYSQL_PORT: db:3306
    env_file:
      - ${DB_ENV_FILE}
    ports:
      - "8081:8080"
    links:
      - db
    volumes:
      - "/data/shelf-data/shelf/${APP_MODULE_NAME}:/root/shelf/"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "2000M"
    depends_on:
      - db

  db:
    image: ${DB_IMAGE}
    env_file:
      - ${DB_ENV_FILE}
    volumes:
      - "/data/shelf-data/shelf/${APP_MODULE_NAME}/mysql-data:/var/lib/mysql"
    ports:
      - "3307:3306"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "2000M"
