version: "3.5"
services:

  app:
    container_name: app
    build: .
    ports:
      - "8081:8080"
    links:
      - "db:my_test"
    environment:
      APP_TYPE_OF_WORK: "server-client"
      MYSQL_PORT: "db:3306"
    volumes:
      - /opt/data:/root/shelf
    depends_on:
      - db

  db:
    container_name: db
    build: mysql_env_docker/
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"




