version: "3.5"
services:

  app:
    container_name: app
    build: .
    ports:
      - "8081:8080"
    links:
      - "db:my_test"
    environment:
      MYSQL_PORT: "db:3306"
    depends_on:
      - db

  db:
    container_name: db
    build: mysql_env_docker/
    ports:
      - "3307:3306"




