version: "3.5"

x-web-app-args: &web-app-args
  START_MODULE_NAME_ARG: "web-app-module"
  APP_VERSION_ARG: "1.0-SNAPSHOT"
  JDK_VERSION: "8"

x-mysql-envs: &mysql-envs
  MYSQL_PORT: "mysql:3306"
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "test"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "my_test"

services:
  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: dockerfile
      args:
        *web-app-args
    environment:
      *mysql-envs
    ports:
      - "8081:8080"
    links:
      - "mysql"
    volumes:
      - /opt/data:/root/shelf
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "2000M"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: mysql_dockerfile
    environment:
      *mysql-envs
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "2000M"