db-config:
  sqlite:
    driverClassName: "org.sqlite.JDBC"
    hibernateDialect: "org.sqlite.hibernate.dialect.SQLiteDialect"
  mysql:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    hibernateDialect: "org.hibernate.dialect.MySQL8Dialect"
    url: "jdbc:mysql://localhost:3307/my_test"
    userName: "test"
    password: "test"

