# shelf config
shelf:
  port: 8082
  home: ${user.home}/shelf
  sqliteDbFile: shelf_sqlite_db.db
  sqliteDbPath: ${shelf.home}/${shelf.sqliteDbFile}
  sqliteDbUrlStart: "jdbc:sqlite://"
  sqliteDbUrl: ${shelf.sqliteDbUrlStart}${shelf.sqliteDbPath}

# app port to start
server.port: ${shelf.port}

# app config
spring.profiles.active: dev

spring.web.resources.static-locations: file:./spring-web-app-module/src/main/resources/static
server.tomcat.keep-alive-timeout: 1000

---

spring:
  config:
    activate:
      on-profile: dev
db-config:
  sqlite:
    driverClassName: "org.sqlite.JDBC"
    hibernateDialect: "org.sqlite.hibernate.dialect.SQLiteDialect"
    url: ${shelf.sqliteDbUrl}
  mysql:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    hibernateDialect: "org.hibernate.dialect.MySQL8Dialect"
    url: "jdbc:mysql://localhost:3307/my_test"
    userName: "test"
    password: "test"
